[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "budget-anator"
version = "1.0.0"
description = "A GUI for journaling"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "mekasu0124", email = "mek0124@proton.me"},
]
license = "MIT"
dependencies = [
    "sqlalchemy>=2.0.0",
    "pyside6>=6.10.2",
    "pyside6-fluent-widgets>=1.11.1",
]

[project.urls]
Homepage = "https://github.com/mek0124/budget-anator"
Repository = "https://github.com/mek0124/budget-anator.git"
Documentation = "https://github.com/mek0124/budget-anator"

[project.scripts]
budgetanator = "app.app:main"

[tool.setuptools]
packages = ["app", "core"]

[tool.setuptools.package-data]
"*" = ["*.py", "assets/*"]